server:
  port: 1200
  servlet:
    context-path: /tasty-town

spring:
  datasource:
    url: jdbc:mysql://localhost/tasty-town
    username: root
    password: 5233

upload:
  file:
    dir: images
order:
  delivery:
     fee: 40


  tax:
    rate: 0.1